{{- if and .Values.database.enabled .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.existingSecret }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
